# Generated by Django 4.0.4 on 2022-05-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipoDocu',
            field=models.CharField(choices=[('Registro civil', 'Registro civil'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de ciudadania', 'Cédula de ciudadania'), ('Cédula de extrangeria', 'Cédula de extrangeria'), ('Pasaporte', 'Pasaporte')], max_length=200, verbose_name='Tipo de documento'),
        ),
    ]
