# Generated by Django 4.0.4 on 2022-05-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='odontologo',
            fields=[
                ('id_odontologo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id odontologo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Odontologo',
                'verbose_name_plural': 'Odontologos',
            },
        ),
    ]
