# Generated by Django 4.0.4 on 2022-05-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Especialidad', '0001_initial'),
        ('Odontologo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Especialidad.especialidad', verbose_name='Especialidad'),
        ),
    ]
