# Generated by Django 4.0.4 on 2022-05-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='address',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(choices=[('Armenia', 'Armenia'), ('Barrancabermeja', 'Barrancabermeja'), ('Barranquilla', 'Barranquilla'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Buga', 'Buga'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Chía', 'Chía'), ('Cúcuta', 'Cúcuta'), ('Duitama', 'Duitama'), ('Florencia', 'Florencia'), ('Fusagasugá', 'Fusagasugá'), ('Girardot', 'Girardot'), ('Honda', 'Honda'), ('Ibagué', 'Ibagué'), ('Ipiales', 'Ipiales'), ('Jamundí', 'Jamundí'), ('Leticia', 'Leticia'), ('Manizales', 'Manizales'), ('Mariquita', 'Mariquita'), ('Medellín', 'Medellín'), ('Mompox', 'Mompox'), ('Montería', 'Montería'), ('Murillo', 'Murillo'), ('Neiva', 'Neiva'), ('Pamplona', 'Pamplona'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Popayán', 'Popayán'), ('Riohacha', 'Riohacha'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('San Antero', 'San Antero'), ('Santa Marta', 'Santa Marta'), ('Santafé de Antioquia', 'Santafé de Antioquia'), ('Sevilla', 'Sevilla'), ('Sincelejo', 'Sincelejo'), ('Sogamoso', 'Sogamoso'), ('Tabio', 'Tabio'), ('Tocancipá', 'Tocancipá'), ('Tolú', 'Tolú'), ('Tuluá', 'Tuluá'), ('Tumaco', 'Tumaco')], max_length=200, verbose_name='Nombre de ciudad'),
        ),
    ]
