# Generated by Django 4.0.4 on 2022-05-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acudiente',
            fields=[
                ('id_acudiente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id acudiente')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del acudiente')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electronico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('Documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documento.documento')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
            },
        ),
    ]
