# Generated by Django 4.0.4 on 2022-05-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_paciente_num_documento'),
        ('Acudiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente', verbose_name='Paciente/Acompañante'),
            preserve_default=False,
        ),
    ]
