# Generated by Django 4.0.4 on 2022-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tto',
            field=models.TextField(max_length=200, null=True, verbose_name='Tratamiento'),
        ),
    ]
