# Generated by Django 4.0.4 on 2022-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_alter_paciente_city_alter_paciente_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='num_documento',
            field=models.IntegerField(default=1, verbose_name='Número de documento'),
            preserve_default=False,
        ),
    ]
