# Generated by Django 4.0.4 on 2022-05-18 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Odontologo', '0001_initial'),
        ('Especialidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Aceptada')),
                ('id_cita', models.AutoField(primary_key=True, serialize=False, verbose_name='Id acudiente')),
                ('paciente', models.CharField(max_length=200, verbose_name='Paciente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('espe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Especialidad.especialidad', verbose_name='Especialidad')),
                ('id_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Odontologo.odontologo', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
